//
//  Aware_details.swift
//  Aware
//
//  Created by Pardeep on 22/04/17.
//  Copyright © 2017 Pardeep. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


struct Aware_details: JSONCompatible {
    var name: String
    var id: Int
    var address: String
    var title: String
    var query: String


    init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        name = json["name"] as? String ?? ""
        id = json["id"] as? Int ?? 0
        address = json["address"] as? String ?? ""
        title = json["title"] as? String ?? ""
        query = json["query"] as? String ?? ""
    }



    init() {
        self.init(json: [:])!
    }



    init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(name: String, id: Int, address: String, title: String, query: String) {
        self.name = name
        self.id = id
        self.address = address
        self.title = title
        self.query = query
    }



    /// This function generate a json dictionary from the model.
    ///
    /// - Parameter useOriginalJsonKey: This parameter take effect only when you have modified a property's name making it different to the original json key. If true, the original json key will be used when generate json dictionary, otherwise, the modified property name will be used as key in the dictionary.
    func jsonDictionary(useOriginalJsonKey: Bool) -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["name"] = name
        dict["id"] = id
        dict["address"] = address
        dict["title"] = title
        dict["query"] = query
        return dict
    }



}



