//
//  JSONCompatible.swift
//  Aware
//
//  Created by Pardeep on 22/04/17.
//  Copyright © 2017 Pardeep. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


protocol JSONCompatible {
    init?(json: [String: Any]?)
    init()
    init?(data: Data?)
    func jsonDictionary(useOriginalJsonKey: Bool) -> [String: Any]
}



