//
//  Root.swift
//  Aware
//
//  Created by Pardeep on 22/04/17.
//  Copyright © 2017 Pardeep. All rights reserved.
//
//  -- auto-generated by JSON2Swift --
//

import Foundation


class Root: JSONCompatible {
    var aware_details: Aware_details
    var message: String


    required init?(json: [String: Any]?) {
        guard let json = json else {return nil}
        aware_details = Aware_details(json: json["aware_details"] as? [String: Any]) ?? Aware_details()
        message = json["message"] as? String ?? ""
    }



    required convenience init() {
        self.init(json: [:])!
    }



    required convenience init?(data: Data?) {
        guard let data = data else {return nil}
        guard let json = (try? JSONSerialization.jsonObject(with: data, options: [])) as? [String: Any] else {return nil}
        self.init(json: json)
    }



    init(aware_details: Aware_details, message: String) {
        self.aware_details = aware_details
        self.message = message
    }



    /// This function generate a json dictionary from the model.
    ///
    /// - Parameter useOriginalJsonKey: This parameter take effect only when you have modified a property's name making it different to the original json key. If true, the original json key will be used when generate json dictionary, otherwise, the modified property name will be used as key in the dictionary.
    func jsonDictionary(useOriginalJsonKey: Bool) -> [String: Any] {
        var dict: [String: Any] = [:]
        dict["aware_details"] = aware_details.jsonDictionary(useOriginalJsonKey: useOriginalJsonKey)
        dict["message"] = message
        return dict
    }



}



